name: build LPADesktop

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: install depdency
      run: sudo apt update && sudo apt-get -y install zip 
    
    - name: docker-compose
      run: docker-compose up
      
    - name: zip artifacts
      run: zip lpadesktop.zip -r target

    - name: Upload release asset
      if: github.event == 'release'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.YOURTOKEN }}
        file: lpadesktop.zip
        tag: ${{ github.ref }}
        name: ${{ github.sha }}
        file_glob: true

    - name: Deliver
      uses: actions/upload-artifact@v2
      with:
        name: Deliver
        path: ./target
